/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_isima_bios_parquet_ParquetJniWrapper */

#ifndef _Included_io_isima_bios_parquet_ParquetJniWrapper
#define _Included_io_isima_bios_parquet_ParquetJniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_isima_bios_parquet_ParquetJniWrapper
 * Method:    openParquetWriter
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_io_isima_bios_parquet_ParquetJniWrapper_openParquetWriter
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     io_isima_bios_parquet_ParquetJniWrapper
 * Method:    destroyParquetWriter
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_parquet_ParquetJniWrapper_destroyParquetWriter
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_isima_bios_parquet_ParquetJniWrapper
 * Method:    writeNext
 * Signature: (JI[J[J)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_parquet_ParquetJniWrapper_writeNext
  (JNIEnv *, jobject, jlong, jint, jlongArray, jlongArray);

/*
 * Class:     io_isima_bios_parquet_ParquetJniWrapper
 * Method:    closeParquetWriter
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_isima_bios_parquet_ParquetJniWrapper_closeParquetWriter
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
