FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends python3 python3-pip git vim net-tools telnet software-properties-common libc6 libstdc++6
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
