/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_isima_bios_sdk_csdk_CSdkDirect */

#ifndef _Included_io_isima_bios_sdk_csdk_CSdkDirect
#define _Included_io_isima_bios_sdk_csdk_CSdkDirect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    initialize
 * Signature: (Ljava/lang/Class;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_initialize
  (JNIEnv *, jobject, jclass, jstring);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    isInitialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_isInitialized
  (JNIEnv *, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    startSession
 * Signature: (Ljava/lang/String;IZLjava/lang/String;Ljava/lang/String;JLio/isima/bios/sdk/csdk/CSdkApiCaller;)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_startSession
  (JNIEnv *, jobject, jstring, jint, jboolean, jstring, jstring, jlong, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    loginBios
 * Signature: (ILjava/nio/ByteBuffer;JLio/isima/bios/sdk/csdk/CSdkApiCaller;)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_loginBios
  (JNIEnv *, jobject, jint, jobject, jlong, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    simpleMethod
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;JLio/isima/bios/sdk/csdk/CSdkApiCaller;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_simpleMethod
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jobject, jlong, jobject, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    genericMethod
 * Signature: (II[Ljava/lang/String;[Ljava/lang/String;Ljava/nio/ByteBuffer;JLio/isima/bios/sdk/csdk/CSdkApiCaller;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_genericMethod
  (JNIEnv *, jobject, jint, jint, jobjectArray, jobjectArray, jobject, jlong, jobject, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    ingestBulkStart
 * Signature: (IIILio/isima/bios/sdk/csdk/InsertBulkExecutor;)J
 */
JNIEXPORT jlong JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_ingestBulkStart
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    ingestBulk
 * Signature: (IJII[Ljava/lang/String;Ljava/nio/ByteBuffer;JLio/isima/bios/sdk/csdk/CSdkApiCaller;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_ingestBulk
  (JNIEnv *, jobject, jint, jlong, jint, jint, jobjectArray, jobject, jlong, jobject, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    ingestBulkEnd
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_ingestBulkEnd
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    checkOperationPermissionNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_checkOperationPermissionNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    endSession
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_endSession
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    allocateBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_allocateBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    releasePayload
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_releasePayload
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    log
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJJJJJJ)V
 */
JNIEXPORT void JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_log
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    currentTimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_currentTimeMillis
  (JNIEnv *, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    getOperationName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_getOperationName
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    listStatusCodesNative
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_listStatusCodesNative
  (JNIEnv *, jobject);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    getStatusName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_getStatusName
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_isima_bios_sdk_csdk_CSdkDirect
 * Method:    writeHelloNative
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_io_isima_bios_sdk_csdk_CSdkDirect_writeHelloNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
