/*
 * Copyright (C) 2025 Isima, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber
 */

#ifndef _Included_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber
#define _Included_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber
 * Method:    subscribe
 * Signature: (JILcom/tieredfractals/tfos/sdk/csdk/reactive/TfosSubscription;)I
 */
JNIEXPORT jint JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber_subscribe(
    JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber
 * Method:    error
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber_error(
    JNIEnv *, jobject, jlong, jint);

/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber
 * Method:    next
 * Signature:
 * (JILcom/tieredfractals/tfos/sdk/csdk/reactive/models/TfosRequestWrapper;Lcom/tieredfractals/tfos/models/TfosRequest;)I
 */
JNIEXPORT jint JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber_next(
    JNIEnv *, jobject, jlong, jint, jobject, jobject);

/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber
 * Method:    complete
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeRequestSubscriber_complete(
    JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
