/*
 * Copyright (C) 2025 Isima, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController */

#ifndef _Included_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController
#define _Included_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController_start(JNIEnv *,
                                                                                      jobject);

/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController_stop(JNIEnv *,
                                                                                     jobject);

/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController
 * Method:    startEchoPipe
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController_startEchoPipe(
    JNIEnv *, jobject);

/*
 * Class:
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController
 * Method:    stopEchoPipe
 * Signature: (I)V
 */
JNIEXPORT void JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultNativeEchoController_stopEchoPipe(
    JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
