/*
 * Copyright (C) 2025 Isima, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class
 * com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge */

#ifndef _Included_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge
#define _Included_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class: com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge_init(JNIEnv *, jobject,
                                                                                 jint);

/*
 * Class: com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge
 * Method:    open
 * Signature: (ILcom/tieredfractals/tfos/sdk/csdk/ReactivePayloadCodec;)J
 */
JNIEXPORT jlong JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge_open(JNIEnv *, jobject,
                                                                                 jint, jobject);

/*
 * Class: com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge
 * Method:    openPipe
 * Signature:
 * (JLcom/tieredfractals/tfos/sdk/csdk/reactive/TfosPublisher;Lcom/tieredfractals/tfos/sdk/csdk/reactive/TfosSubscriber;Lcom/tieredfractals/tfos/sdk/csdk/reactive/impl/ResponsePusher;)I
 */
JNIEXPORT jint JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge_openPipe(
    JNIEnv *, jobject, jlong, jobject, jobject, jobject);

/*
 * Class: com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge
 * Method:    closePipe
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge_closePipe(JNIEnv *,
                                                                                      jobject,
                                                                                      jlong, jint,
                                                                                      jboolean);

/*
 * Class: com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_tieredfractals_tfos_sdk_csdk_reactive_impl_DefaultTfosNativeBridge_close(JNIEnv *, jobject,
                                                                                  jlong);

#ifdef __cplusplus
}
#endif
#endif
