# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install general prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl wget gnupg
        sudo apt-get install -y ca-certificates software-properties-common lsb-release build-essential
        sudo apt-get install -y libxml2-utils python3-dev python3-pip python3-venv
        sudo apt-get install -y virtualenv cmake libssl-dev libboost-all-dev net-tools certbot pkg-config
        sudo apt-get install -y jq libtool unzip ninja-build graphviz ncdu
        sudo apt-get install -y libjna-jni libjna-java libpq-dev chromium-browser
    - name: Install apache arrow
      run: |
        wget https://packages.apache.org/artifactory/arrow/ubuntu/apache-arrow-apt-source-latest-jammy.deb
        sudo apt-get install -y ./apache-arrow-apt-source-latest-jammy.deb
        sudo apt-get update
        sudo apt-get install -y libarrow-dev libparquet-dev
    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Install node requirements
      run: |
        wget https://deb.nodesource.com/setup_lts.x
        sudo bash ./setup_lts.x
        rm -f ./setup_lts.x*
        sudo apt-get update
        sudo apt install nodejs
        sudo npm install yarn -g
        sudo npm install -g n
        sudo n 20.15.0
    - name: Build with Maven
      run: mvn install
